window.blackBookNames = [
  "Abby",
  "Abousieiman, Joanna",
  "Adam, Nick",
  "Agag, Alejandro",
  "Agnew, Marie Claire & John",
  "Alai, Azzedine",
  "Aldridge, Saffron",
  "Alexander, Pam",
  "Algranti, Giacomo",
  "Allan, Paul",
  "Allan, Nick & Sarah",
  "Albermarle, Rufus & Sally",
  "Althorp, Charlie",
  "Alun-Jones, Carella",
  "Alun-Jones, Jeremy & Deborah",
  "Alvarez, Senor Vicente",
  "Amon, Mr Philippe",
  "Amon, Roberta & Maurice",
  "Anastos, Lisa",
  "Anderson, Lulu",
  "Appleby, Robert & Alex",
  "Arango, Maite",
  "Arellano, Victor",
  "Arion, Joaquin Fernandez de Cordoba",
  "Arion, Fernando",
  "Armstrong, Arthur & Cathy",
  "Aron, Herve & Marine",
  "Assaf, Charlotte & Vittorio",
  "Aznar, Jose",
  "Ash, Lorinda",
  "Ashley & Allegra Hicks",
  "Ashley, Nick & Ari",
  "Astaire, Mr Simon",
  "Astor, Viscount William",
  "Atkin, Helene",
  "Atkin, Mike & Ami",
  "Baddeley, Jean",
  "Bahrke, Peter",
  "Baker, Danny",
  "Bakhtiar, Shariar",
  "Balazs, Andre",
  "Baldwin, Alec",
  "Bamford, George/Alice",
  "Bamford, Sir Anthony and Lady C",
  "Bands, Doug",
  "Banon, Javier",
  "Barham, Nicholas & Gretal",
  "Barnes, Peter",
  "Barnett, Craig",
  "Bastone, Hillary",
  "Batstone, Hillary",
  "Batstone, Tim",
  "Benson, Steven",
  "Beaumont, Lord & Lady",
  "Beckwith, Tamara",
  "Beizberg, Lisa",
  "Bentinck, Baron",
  "Berggruen, Nicolas",
  "Berkman, Bill",
  "Bernard, Tara",
  "Birchall, Martyn",
  "Birley, Robin",
  "Bismarck, Debbie & Bo la Von",
  "Bismark, Vanessa Von",
  "Bisson, Jean Marc",
  "Bjorlin, Jean Paul",
  "Black, Conrad & Barbara",
  "Blaine, David",
  "Blair, Tony",
  "Bloomberg, Mike",
  "Boardman, Samantha",
  "Boden, Johnie & Sophie",
  "Bodini, Daniel",
  "Boisgelin, Edward de",
  "Boisguilbert, Pierre de",
  "Bond, Anabeile",
  "Bookis, Nicholas",
  "Booth, Mark & Lauren",
  "Boothe, Christina A.",
  "Borgese, Pauio",
  "Bonomi, Andrea & Giola",
  "Borrico, Michael",
  "Boucherie, Sylvianne",
  "Bourke, Rick",
  "Bowies, Hamisb",
  "Brachetti Peretti, Fernando",
  "Brachetti, Hugo",
  "Braine, Caroline",
  "Braine, Ms Katie & Serge",
  "Bram, Ben",
  "Brand, Tony",
  "Brandolini d'Adda",
  "Brandolini, Nuno & Muriel",
  "Brandt, Peter",
  "Branson, Richard",
  "Briatore, Flavio",
  "Broadhurst, Julia",
  "Broglie, Louis Albert de",
  "Brooks, Miranda",
  "Brother",
  "Brown, Chris & Alison",
  "Bruce, James & Lucinda",
  "Bryer, Tania",
  "Buck, Joan Juliet",
  "Buffet, Jimmy & Jane",
  "Bull, Bartle",
  "Bullough, Hamish and Emma",
  "Burckle, Ron",
  "Burney, Mr Jules",
  "Burtril, Martin",
  "Bushnell, Candice",
  "Butter, Charlie",
  "Byng, Robert",
  "Cadenet de, Alain",
  "Calacanis, Jason",
  "Caledon, Nicky",
  "Calivo-Pfatero, Mario/Ariadne",
  "Cambell, Roddy",
  "Cambell, Alistar",
  "Camerana, Giancarlo",
  "Cammy",
  "Campbell, Naomi",
  "Campo del, Brooke & Emilio",
  "Candole, Andrew de",
  "Candy, Nicholas A C",
  "Candy ana Candy Ltd",
  "Caspar, Nacho",
  "Gaul, Harriett",
  "Geary, Tim",
  "Gelardin, Jack",
  "German-Ribon, Catriona",
  "Gibson, Caroline",
  "Gillfillan, Andrew",
  "Gillford, Lord & Lady",
  "Gillmour, Andrew & Emma",
  "Ginsberg, Gary",
  "Gittles, Howard",
  "Giussani, Luca",
  "Glanville, Mary",
  "Glass, Charlie",
  "Glentworth, Edmund & Emily",
  "Goess, Pilar",
  "Goldberg, Ellen",
  "Goldsmith, Isabel",
  "Golinkin, Sandy",
  "Gomez, Thomas",
  "Gomme, William",
  "Gordon, Jacobo",
  "Gore, Juliet",
  "Gottlieb, Steve",
  "Goulandris, Dimitri & Emma",
  "Granby, David",
  "Grange, Jacques",
  "Grant, Jamie",
  "Greece, MC & Pavlos",
  "Green, Deborah",
  "Green, Jeremy",
  "Gregg, Geordte & Katherine",
  "Grenfell, Natasha",
  "Griffen, Ted",
  "Griscom, Nina",
  "Grabau, Lorenzo",
  "Greece, Princess Olga",
  "Green, Judy",
  "Gross, Pamela & Jimmy Finkelstein",
  "Hammond, Dana",
  "Hanson, The Hon Robert",
  "Hapsburg, Marie",
  "Harvey, Victoria",
  "Harvie-Watt, Isabelle",
  "Haslam, Nick",
  "Hatkoff, Craig & Jane",
  "Hauteville, Marc de",
  "Hay, Henry & Patricia",
  "Hayworth, Reggie",
  "Hazel-Iveagh, Clare",
  "Hearn, Barry & Susan",
  "Hefner III, Bob",
  "Heiden, Lisa",
  "Heineken, Mr Freddie",
  "Helvin, Marie",
  "Herbert, Jason",
  "Herrera, Juan & Helen",
  "Hicks, India",
  "Hill, Anthony",
  "Himmelstein, Howard",
  "Hirsch, Jeff",
  "Hissom, Robert & Andrea",
  "Hoffman, Dustin",
  "Hoffman, Hetty",
  "Hoffman, Jessica",
  "Holland-Martin, Ben",
  "Horne, Adam Tierney",
  "Hovenian, Nina",
  "Howegego, Lucy",
  "Hsu, Peter",
  "Hunt, Laura",
  "Hunter Gordon, Kit & Georgina",
  "Hunter, Carlyn & Laurie",
  "Huntsman, Jon & Mary Kaye",
  "Hurd, Nick & Kim",
  "Hurley, Liz",
  "Hussain, Ayia",
  "Hussey, Simon",
  "Hutley, Henry",
  "Hutley, Lulu & Edward",
  "Hutton, Lauren",
  "Ind, Charlie",
  "Inzerilio, Gerard J.",
  "Ireland, George",
  "Irvine, Eddie",
  "Isamel, Abdullah",
  "Isham, Chris",
  "Jackson, Michael",
  "Jacobson, Julian",
  "Jagger, Mick",
  "James, Susie",
  "Jeffries, Tim",
  "Johnson, Richard & Nadine",
  "Johnson, Lucy",
  "Jones, Ann & Mick",
  "Josephson, Barry & Jackie",
  "Katz, Anton & Robin Plant",
  "Keeling, Sarah",
  "Kegan, Rory",
  "Keidan, Jon",
  "Keller, Georgia",
  "Knight, Leo & Art",
  "d'Abo, Mrs Jennifer",
  "d'Abo, Henri & Tatiana",
  "d'Arenberg, Prince Pierre",
  "Dabbagh, Amr A.",
  "Davies, David & Linda",
  "Dahl, Sophie",
  "Davis, Michael",
  "Dartmouth, William",
  "Davies, Jeff",
  "Day, Nick and Heather",
  "de Andrade, Marcelo",
  "de Baecque, Patrick",
  "De Cadenet, Alain",
  "De Soto, Fernando",
  "Dolbey, Alex & Suzie",
  "Douglas, Diandra",
  "Driver, Minnie",
  "Dubb, Anthony V.",
  "Dunne, Griffin",
  "Dunne, Philip & Dominice",
  "Duong, Anh",
  "Durso, Luigi",
  "Duthie, John & Charlotte",
  "Dzhabrailou, Umar",
  "Ecclestone, Bernie",
  "Edwards, Andrew & Tracy",
  "Elian, Johnathan",
  "Elias, Brian",
  "Ellasch, Johan & Amanda",
  "Ellingworth, Charlie & Amanda",
  "Elliot, Ben",
  "Elliot, Gail & Joe Coffey",
  "Ellison, Mandy & Ralph",
  "Erba, Noona",
  "Espirito Santo, Manuel and Ros",
  "Estlin, Jean-Marc",
  "Elwes, Anabel",
  "Estrada Juffali, Christina",
  "Evans, Chris",
  "Evehart, Angie",
  "Faber, David",
  "Faber, Sally & Brook Johnson",
  "Faibairn, Charlotte & Hamish Fraser",
  "Fairfax, The Hon Rupert",
  "Fairweather, Natasha",
  "Fakhre, Armando & Jasmine",
  "Fakhre, Danny & Christine",
  "Fanjul, Pepe",
  "Faulkner, Terence & Cornelia",
  "Feeley, Fiona",
  "Fekkai, Frederic",
  "Feldman, Andrew",
  "Felix, Helena",
  "Fell, David & Anne",
  "Ferragamo, Leonardo & Beatrice",
  "Ferranti, Hugo",
  "Ferry, Brian",
  "Fiennes, Martin",
  "Fiennes, Ralph",
  "Figg, Christopher & Lillie",
  "Finch, Charles",
  "Finkelstein, Howard",
  "Fifer, Chuck",
  "Firyal, Princess",
  "Fisher, Dan",
  "Flick, Mook",
  "Foman, Bobby & Jeanette",
  "Forbes, Zandy",
  "Forbes, Chris (Kip) Astrid",
  "Ford, Katie",
  "Ford, Tom & Richard Buckley",
  "Formby, Nicola",
  "Forte, Rocco & Altair",
  "Fox, Andrew",
  "Fox, William & Lucinda",
  "Fraiser, Violet",
  "Francey, Kathy",
  "Fraysse, Isabel",
  "Freud, Mathew",
  "Frost, Mr David & Lady Carina",
  "Frostrup, Marietta",
  "Fry, Cosmo & Amanda",
  "Furstenberg, Heinrich Milana",
  "Furstenburg, Alex, Alexandra V.",
  "Gaetani, Gelasio",
  "Gaetani, Rufredo",
  "Ganero, Mario Jr.",
  "Ganoza, Esteban Juan",
  "Garcia, Ludmila",
  "Gardner, Adam",
  "Garland, Michael",
  "Garson, Jeremy",
  "Gilmour, Andrew & Emma",
  "Gittis, Howard",
  "Gregg, Geordie & Katherine",
  "Tholstrup, Moegens",
  "Tholstrup, Paola",
  "Thompson, Barnaby",
  "Tisch, David",
  "Tisch, Merry & Jimmy",
  "Tollman, Bea",
  "Tollman, Brett",
  "Tollman, Syrie & Gavin",
  "Toub, Veronica (Busson)",
  "Trump, Ivana",
  "Trump, Ivanka",
  "Van Straubenzee, William",
  "Varsavsky, Martin",
  "Velasquez, Patricia",
  "Verdin, Julia",
  "Verdin-Mulot, Annie & JP",
  "Veronis, Jane",
  "Villeneuve, Jacques",
  "Vittadini, Emanuele A.",
  "Vittoz, Patrick",
  "Von Habsburg, Francesca",
  "Von Hase, Bettina",
  "Waksal, Sam",
  "Wallace, Mike",
  "Wasserman, Casey & Laura",
  "Waterman, Felicity",
  "Watson, Victoria",
  "Webb, Veronica",
  "Weidenfeld, Lord",
  "Weinstein, Bob",
  "Weintraub, Harriet",
  "Westheimer, Ruth Dr.",
  "White, Victoria",
  "Whitworth, Alan & Wendy",
  "Wienberg, Anouska and Mark",
  "Wiesel, Dr Eli and Marion",
  "Wigram, Lionel and Lydia",
  "Williams, Alexandra & Nick",
  "Williams-Ellis, David & Serena",
  "Willis, Rebecca",
  "Wilmot-Sitwell, Alex",
  "Wilson, Carter",
  "Windisch Gratz, Manfred",
  "Winn, Steve",
  "Wolper, Carol",
  "Woodall, Trinny",
  "Woodward, Shaun & Camilla",
  "Wyatt, Steve & Cate",
  "Yamani, Mai",
  "Yariv, Zghoui",
  "Yates, Andrew (Piggy)",
  "Young, Toby",
  "Younger, Tracy & Lee, Greg",
  "Yugoslavia, Dimitri",
  "Yugoslavia, Prince Michel of",
  "Yugoslavia, Serge de",
  "Zacks, Gordon",
  "Zaies, Alexi",
  "Zangrillo, Paige & Bob",
  "Zavvauri, Waleed",
  "Ziikha, Bettina",
  "Zecher, Bibi and Adrian",
  "Zeff, Mark",
  "Zeiler, John",
  "Zevi, Dino & Rosi",
  "Zipp, Brian",
  "Dionne, Ryan",
  "Geffert, Scott",
  "Joseph & Fiorina Rueda",
  "Kelfen, Sarah",
  "Kelly, Brian",
  "Maxwell, Ghislaine",
  "Mitrovich, Andrea",
  "Cecilia Szajman",
  "Ganero, Mario Sr.",
  "Ricardo",
  "Cristina Bello",
  "Alaia, Azzedine",
  "Epstein, Jeffrey",
  "Experton, Marie Joseph",
  "Gerard",
  "Junot, Philippe",
  "Lagardere, Betty",
  "Pinto, Alberto",
  "Vieira Cotrin, Valdson",
  "Adler, Frederick (Fred) & Cath",
  "Andersson, Eva",
  "Barrett, Anthony",
  "Barrett, Jonathan",
  "Beck, Jen",
  "Benamou, Albert",
  "Biddle-Hakim, Sophie",
  "Bjornin, Nadia",
  "Black, Leon",
  "Borden, David",
  "Bovino, Kelly",
  "Brown, Coco",
  "Campos, Michelle",
  "Cayne, Jimmy",
  "Chou, Silas",
  "Daniel",
  "Davison, Dayle",
  "Deison, George",
  "Derby, Catherine",
  "Dershowitz, Alan (likely \"Wah\" OCR error for Alan)",
  "Engle, Don",
  "Edelman, Gerald Dr.",
  "Epstein, Mark",
  "Glick, Howard",
  "Gold, Bob",
  "Goodman, Bob",
  "Gray, Vicki",
  "Griaznove, Svetlana",
  "Guggenheim, Eileen",
  "Harold Mollin",
  "Hashemi, Jaliia",
  "Hedberg, Gregory",
  "Heii, Paula",
  "Hunter, Joey",
  "Indyke, Darren K.",
  "Isaacson, Walter",
  "James, Randy",
  "Jampanoi, Myiene",
  "Jarecki, Gloria",
  "Jarecki, Henry Dr.",
  "Johananoff, Pamela",
  "Johnson, Lily",
  "Johnson, Elizabeth (Libit)",
  "Kerry, Sen. John",
  "Kessier, Jack",
  "Kincaid, Kristina",
  "Kosslyn, Steve",
  "Lang, Adam Perry",
  "Leach, Robin",
  "Leese, Nick",
  "Lopez (Buklarewicz)",
  "Lundberg, Marc",
  "Luntz, Melinda",
  "McMillen, C. Thomas",
  "Merrit, Jerry",
  "Middleton, Mark",
  "Minsky, Marvin",
  "Mitchell, David",
  "Mitchell, Senator George",
  "Morrison, Larry",
  "Myhrvold, Nathan",
  "Newcombe, Timothy W.",
  "Newman, Larry Esq.",
  "Nowak, Martin",
  "Oatman, Bob",
  "Ouertani, Selma",
  "Ovitz, Michael",
  "Packer, Mark",
  "Pagano, Joe",
  "Perlman, Itzhak",
  "Pete",
  "Phillips, Lisa",
  "Pivar, Stuart",
  "Preece, Dara",
  "Quinn, Thomas H.",
  "Ranieri, Lewis S.",
  "Razek, Ed",
  "Rockefeller, David",
  "Rodgers, Dave",
  "Rosovsky, Henry",
  "Ross, David",
  "Sacks, Oliver Dr.",
  "Schaeffer, Stan",
  "Schantz, Jeffrey",
  "Schoettle, Douglas A.",
  "Shadow, Monty",
  "Shaeffer, David",
  "Snyder, Richard & Laura",
  "Sowell, Dottle",
  "Spector, Warren",
  "Staley, Jes",
  "Stark, Caroline",
  "Steel, Kim",
  "Stein, Andrew",
  "Stock, Ann",
  "Stone, Linda",
  "Stroll, Lawrence S.",
  "Tafoya, Craig",
  "Tobiason, Larry",
  "Trump, Donald",
  "Trust, Marty",
  "Trossle, Bob",
  "Tuckerman, Steve",
  "Ugland, Peg",
  "Vaiukas, Tony",
  "Visoski, Larry",
  "Wachner, Linda",
  "Wahl, Francis",
  "Waifaert, Alexia",
  "Wasche, Cristalle",
  "Wexner, Les",
  "Whitehead, Jim",
  "Wofman, Herb",
  "Zuckerman, Mort",
  "Blachon, Magali",
  "Barnett, Richard",
  "Miller, Charles",
  "Fontaniila, Lynn & Jojo",
  "Gaston, Steve",
  "Hamblin, Sue",
  "Tintjall, Brent",
  "CoSes, Alan",
  "Martin, Tim/Debbie Stewart",
  "Marline",
  "O'Neil, Nessa",
  "Outred, Anthony",
  "Ray, John",
  "Tobias, Maxine",
  "Yara",
  "Birnbaum, Dr",
  "John Scobell",
  "Joanna Abousfeiman",
  "Saffron Aldridge",
  "Nick Adam",
  "Alejandro Agag",
  "Marie Claire Agnew",
  "John Agnew",
  "Azzedine Alaï",
  "Pam Alexander",
  "Giacomo Algranti",
  "Paul Allan",
  "Nick Allan",
  "Sarah Allan",
  "Rufus Albermarle",
  "Sally Albermarle",
  "Charlie Althorp",
  "Carella Alun-Jones",
  "Jeremy Alun-Jones",
  "Deborah Alun-Jones",
  "Senor Vicente Alvarez",
  "Mr Philippe Amon",
  "Roberta Amon",
  "Maurice Amon",
  "Lisa Anastos",
  "Lulu Anderson",
  "Robert Appleby",
  "Alex Appleby",
  "Maite Arango",
  "Victor Arellano",
  "Joaquin Fernandez de Arion",
  "Fernando Arion",
  "Arthur Armstrong",
  "Cathy Armstrong",
  "Herve Aron",
  "Marine Aron",
  "Charlotte Assaf",
  "Vittorio Assaf",
  "Lorinda Ash",
  "Allegra Hicks Ashley",
  "Nick Ashley",
  "Ari Ashley",
  "Mr Simon Astaire",
  "Viscount William Astor",
  "Helene Atkin",
  "Mike Atkin",
  "Ami Atkin",
  "Jean Baddeley",
  "Peter Bahrke",
  "Danny Baker",
  "Shariar Bakhtiar",
  "Andre Balazs",
  "Alec Baldwin",
  "George Bamford",
  "Alice Bamford",
  "Sir Anthony Bamford",
  "Lady C Bamford",
  "Doug Bands",
  "Clive Bannister",
  "Javier Banon",
  "Nicholas Barham",
  "Gretal Barham",
  "Peter Barnes",
  "Craig Barnett",
  "Hillary Bastone",
  "Hillary Batstone",
  "Tim Batstone",
  "Natasha Batstone",
  "Lorenzo Baumer",
  "Lord Beaumont",
  "Lady Beaumont",
  "Tamara Beckwith",
  "Lisa Beizberg",
  "Nicolas Berggruen",
  "Bill Berkman",
  "Tara Bernard",
  "Martyn Birchall",
  "Robin Birley",
  "Debbie Bismarck",
  "Bo la Von Bismarck",
  "Vanessa Von Bismark",
  "Jean Marc Bisson",
  "Jean Paul Bjorlin",
  "Conrad Black",
  "Barbara Black",
  "David Blaine",
  "Tony Blair",
  "Kay Secrett",
  "Mike Bloomberg",
  "Samantha Boardman",
  "Johnie Boden",
  "Sophie Boden",
  "Daniel Bodini",
  "Edward de Boisgelin",
  "Pierre de Boisguilbert",
  "Anabeille Bond",
  "Nicholas Bookis",
  "Mark Booth",
  "Lauren Booth",
  "Christina A Boothe",
  "Paulo Borgese",
  "Andrea Bonomi",
  "Giola Bonomi",
  "Michael Borrico",
  "Sylvianne Boucherie",
  "Rick Bourke",
  "Hamish Bowles",
  "Fernando Brachetti Peretti",
  "Hugo Brachetti",
  "Caroline Braine",
  "Katie Braine",
  "Serge Braine",
  "Ben Bram",
  "Tony Brand",
  "Georgina Brandolini d’Adda",
  "Nuno Brandolini",
  "Muriel Brandolini",
  "Peter Brandt",
  "Richard Branson",
  "Flavio Briatore",
  "Julia Broadhurst",
  "Louis Albert de Broglie",
  "Chris Brown",
  "Alison Brown",
  "James Bruce",
  "Lucinda Bruce",
  "Tania Bryer",
  "Joan Juliet Buck",
  "Jimmy Buffet",
  "Jane Buffet",
  "Bart Bull",
  "Hamish Bullough",
  "Emma Bullough",
  "Ron Burckle",
  "Jules Burney",
  "Martin Burtril",
  "Candice Bushnell",
  "Charlie Butter",
  "Robert Byng",
  "Alain Cadenet de",
  "Jason Calacanis",
  "Nicky Caledon",
  "Mario Calvo-Platero",
  "Ariadne Calvo-Platero",
  "Roddy Campbell",
  "Alistar Campbell",
  "Giancarlo Camerana",
  "Naomi Campbell",
  "Brooke Campo del",
  "Emilio Campo del",
  "Andrew de Candole",
  "Nicholas A C Candy",
  "Kathy Francey",
  "Clive Cooke",
  "Esperanza Sobrino",
  "Andrew Solomon",
  "Peter Soros",
  "Fernando Soto",
  "Jaime de Soto",
  "Hamilton South",
  "Kevin Spacey",
  "Hugo Squire",
  "Edward St. Bris",
  "Caroline Stanburry",
  "Thomas Starzewski",
  "Chris Steenkamp",
  "Nina Steenkamp",
  "Andrew Stengel",
  "Rick Stengel",
  "Mary Stengel",
  "Alison Stern",
  "Leonard Stern",
  "Harry Tennenbaum",
  "Eduardo Teodorani-Fabbri",
  "Baroness Francesca Theilmann",
  "Catherine Theodoli",
  "Moegens Tholstrup",
  "Paola Tholstrup",
  "Barnaby Thompson",
  "David Tisch",
  "Merry Tisch",
  "Jimmy Tisch",
  "Anne Irish",
  "Andrew Irish",
  "Ignacio Alvarez de Toledo",
  "Emily Todhunter",
  "Bea Tollman",
  "Brett Tollman",
  "Syrie Tollman",
  "Gavin Tollman",
  "Wyne Tollman",
  "Veronica Toub",
  "Ivana Trump",
  "Ivanka Trump",
  "William Van Straubenzee",
  "Martin Varsavsky",
  "Patricia Velasquez",
  "Julia Verdin",
  "Annie Verdin-Mulot",
  "JP Verdin-Mulot",
  "Jane Veronis",
  "Carmine S. Vilfani",
  "Jacques Villeneuve",
  "Emanuele A. Vittadini",
  "Marco Vittorelli",
  "Patrick Vittoz",
  "Charles Vivian Smith",
  "Francesca Von Habsburg",
  "Bettina Von Hase",
  "Rupert Wainright",
  "Sam Waksal",
  "Mike Wallace",
  "Ozzie Warner",
  "Mandy Warnford-Davis",
  "Casey Wasserman",
  "Laura Wasserman",
  "Eric Wachmeister",
  "David Wagner",
  "Barbara Walters",
  "Kevin Ward",
  "David Wassong",
  "Lucy Wastnage",
  "Felicity Waterman",
  "Victoria Watson",
  "Veronica Webb",
  "Lord Weidenfeld",
  "Jason Weinberg",
  "Bob Weinstein",
  "Harriet Weintraub",
  "Ruth Westheimer",
  "Lally Weymouth",
  "Somers White",
  "Victoria White",
  "Michael White",
  "Victoria White O'Gara",
  "Alan Whitworth",
  "Wendy Whitworth",
  "Jim Wiai",
  "Anouska Wienberg",
  "Mark Wienberg",
  "Eli Wiesel",
  "Marion Wiesel",
  "Lionel Wigram",
  "Lydia Wigram",
  "Alexandra Williams",
  "Nick Williams",
  "David Williams-Ellis",
  "Serena Williams-Ellis",
  "Rebecca Willis",
  "Alex Wilmot-Sitwell",
  "FI Wilmot-Sitwell",
  "Carter Wilson",
  "Manfred Windisch Gratz",
  "Tim Windsor-Taylor",
  "Helen Windsor-Taylor",
  "Steve Winn",
  "Elizabeth Winston",
  "George Wrppie",
  "Carol Wolper",
  "Andy Wong",
  "Theodore Wong",
  "Trinny Woodall",
  "Emily Woods",
  "Carrie Woods",
  "Alexa Woodward",
  "Shaun Woodward",
  "Camilla Woodward",
  "Marg Worcester",
  "Marc Worcester",
  "Jim Wyatt",
  "Steve Wyatt",
  "Cate Wyatt",
  "Mai Yamani",
  "Zghoui Yariv",
  "Andrew Yates",
  "Waleed Zavvauri",
  "Bettina Ziikha",
  "Bibi Zecher",
  "Adrian Zecher",
  "Mark Zeff",
  "John Zeiler",
  "Dino Zevi",
  "Rosi Zevi",
  "Brian Zipp",
  "Ryan Dionne",
  "Scott Geffert",
  "Fiorina Rueda",
  "Joseph Rueda",
  "Sarah Kelfen",
  "Ghislaine Maxwell",
  "Andrea Mitrovich",
  "Robert Goldberg",
  "Frank Bowling",
  "Marc",
  "Mario Ganero",
  "Rob Bovrran",
  "Sharon Mulvany",
  "Azzedine Alaia",
  "Jean Marie",
  "Frank",
  "Valdson Colon",
  "Marie Joseph Experton",
  "Philippe Junot",
  "Betty Lagardere",
  "Stephane Couladx",
  "Geraldine Talavei",
  "Madame Lemercier",
  "Faiza",
  "Anne-France",
  "Claudia Kadida",
  "Debbie",
  "Marie Francois",
  "Rosemary",
  "Alexandria",
  "Caroina",
  "Caro he",
  "Debra Wakshal",
  "Isabelle",
  "Stephanf",
  "Baslien",
  "Karine",
  "Laelitia",
  "Magdall",
  "Francois",
  "Donna",
  "Yelena",
  "Nadia",
  "Tanya",
  "Alberto Pinto",
  "Linda",
  "Serge Soquet",
  "Serge Boquet",
  "Cynthia",
  "Clauds",
  "Danielle",
  "Jean",
  "Yves",
  "Chantal",
  "Valdson",
  "Pierre",
  "Mr & Mrs Mieie",
  "Bettinalz",
  "Elisa Eshed",
  "Duud Efrat Evani",
  "Avi Gil",
  "Arik Gutman",
  "Vakhof Neima",
  "Ehud Olmert",
  "Frederick Adler",
  "Cath Adler",
  "Eva Andersson",
  "Anthony Barrett",
  "Jonathan Barrett",
  "Jen Beck",
  "Albert Benamou",
  "Sophie Biddle-Hakim",
  "Gilbert Hakim",
  "Nadia Bjorin",
  "Leon Black",
  "David Borden",
  "Kelly Bovino",
  "Coco Brown",
  "Michelle Campos",
  "Jimmy Cayne",
  "Silas Chou",
  "Dayle Davison",
  "George Deison",
  "Catherine Derby",
  "Alan Dershowitz (corrected from OCR variant)",
  "Don Engle",
  "Gerald Edelman",
  "Howard Glick",
  "Bob Gold",
  "Bob Goodman",
  "Vicki Gray",
  "Svetlana Griaznove",
  "Eileen Guggenheim",
  "Gregory Hedberg",
  "Paula Heii",
  "Joey Hunter",
  "Darren Indyke",
  "Randy James",
  "Myiene Jampanoi",
  "Gloria Jarecki",
  "Henry Jarecki",
  "Pamela Johananoff",
  "Walter Isaacson",
  "Kristina Kincaid",
  "Steve Kosslyn",
  "Adam Lang",
  "Robin Leach",
  "Nick Leese",
  "Karin Lopez",
  "Marc Lundberg",
  "Melinda Luntz",
  "C. Thomas McMillen",
  "Irish, Anne & Andrew",
  "Titopupolo, Sonia",
  "Todhunter, Emily",
  "Toledo, Ignacio Alvarez de",
  "Tollman, Wyne",
  "Vilfani, Carmine S.",
  "Vittorelli, Marco",
  "Vivian Smith, Charles",
  "Wainright, Rupert",
  "Warner, Ozzie",
  "Warnford-Davis, Mandy",
  "Wachmeister, Eric",
  "Wagner, David",
  "Walters, Barbara",
  "Ward, Kevin",
  "Wassong, David",
  "Wastnage, Lucy",
  "Weinberg, Jason",
  "Weymouth, Lally",
  "White, Somers",
  "White, Michael",
  "White O’Gara, Victoria",
  "Wienberg, Anouska & Mark",
  "Wiesel, Eli Dr. & Marion",
  "Wigram, Lionel & Lydia",
  "Windsor-Taylor, Tim & Helen",
  "Winston, Elizabeth",
  "Wong, Andy",
  "Wong, Theodore",
  "Woods, Emily & Carrie",
  "Worcester, Marg & Marc",
  "Wyatt, Jim",
  "Younger, Tracy & Greg Lee",
  "Zilkha, Bettina",
  "Zecher, Bibi & Adrian",
  "Rueda, Joseph & Fiorina",
  "Szajman, Cecilia",
  "Bello, Cristina",
  "Dershowitz, Alan",
  "Hell, Paula",
  "Kessler, Jack",
  "Merritt, Jerry",
  "Sowell, Dottie",
  "Morgan Fairchild (actress, known from TV shows like \"Dallas\" and \"Falcon Crest\")",
  "Suzanne Ircha (wife of Woody Johnson, New York Jets owner and former Trump ambassador to the UK; also noted as a friend of Melania Trump)",
  "Carl Icahn (billionaire financier and corporate raider)",
  "John A. Catsimatidis (supermarket magnate, Gristedes owner, and Trump supporter)",
  "Cristina Greeven (wife of former CNN anchor Chris Cuomo)",
  "Marty Peretz (former owner/publisher of The New Republic)",
  "Steven Rattner (former auto-industry czar, financier)",
  "Prince Andrew",
  "Stephen Hawking",
  "Sergey Brin",
  "Anne Wojcicki",
  "Reid Hoffman",
  "Howard Lutnick",
  "Joanna Rubinstein",
  "Ehud Barak",
  "David Copperfield",
  "Bill Clinton",
  "Les Wexner",
  "Roger Schank",
  "Andrew Farkas",
  "Thorbjorn Jagland",
  "Sultan Ahmed bin Sulayem",
  "Jeffrey Epstein",
  "Sarah Kellen",
  "Nadia Marcinkova",
  "Donald Trump",
  "Alan Dershowitz",
  "Chris Tucker",
  "Chris Evans",
  "Jean-Luc Brunel",
  "Doug Band",
  "Woody Allen",
  "Soon-Yi Previn",
  "Bill Gates",
  "Lawrence Summers",
  "Itzhak Perlman",
  "Eva Andersson-Dubin",
  "Sarah Ferguson",
];

window.islandFlagNames = [
  "Prince Andrew",
  "Stephen Hawking",
  "Sergey Brin",
  "Anne Wojcicki",
  "Reid Hoffman",
  "Howard Lutnick",
  "Joanna Rubinstein",
  "Ehud Barak",
  "David Copperfield",
  "Ghislaine Maxwell",
  "Bill Clinton",
  "Les Wexner",
  "Roger Schank",
  "Andrew Farkas",
  "Thorbjorn Jagland",
  "Sultan Ahmed bin Sulayem",
];

window.nameTagByName = {
  "Prince Andrew": "confirmed",
  "Stephen Hawking": "confirmed",
  "Sergey Brin": "confirmed",
  "Anne Wojcicki": "confirmed",
  "Reid Hoffman": "confirmed",
  "Howard Lutnick": "confirmed",
  "Joanna Rubinstein": "confirmed",
  "Ehud Barak": "confirmed",
  "David Copperfield": "confirmed",
  "Ghislaine Maxwell": "confirmed",
  "Bill Clinton": "alleged",
  "Les Wexner": "confirmed",
  "Roger Schank": "confirmed",
  "Andrew Farkas": "confirmed",
  "Thorbjorn Jagland": "confirmed",
  "Sultan Ahmed bin Sulayem": "confirmed",
};

window.personInfoByName = {
  "Jeffrey Epstein": "Reported context: listed as owner/operator in the flight-log discussion.",
  "Ghislaine Maxwell": "Reported context: described as a frequent passenger and operational associate.",
  "Sarah Kellen": "Reported context: described as an assistant/scheduler appearing frequently in logs.",
  "Nadia Marcinkova": "Reported context: described as a pilot/associate appearing repeatedly in early logs.",
  "Bill Clinton": "Reported context: described as frequently mentioned in high-profile flight-log contexts.",
  "Prince Andrew": "Reported context: described as a frequently mentioned high-profile passenger.",
  "Donald Trump": "Reported context: described as appearing on a limited number of flights in earlier years.",
  "Alan Dershowitz": "Reported context: described as appearing on multiple flights.",
  "Kevin Spacey": "Reported context: described as appearing on the Africa trip context.",
  "Chris Tucker": "Reported context: described as appearing on the Africa trip context.",
  "Naomi Campbell": "Reported context: described as appearing on multiple flights in early 2000s logs.",
  "Chris Evans": "Reported context: described as limited/unclear in logs.",
  "Jean-Luc Brunel": "Reported context: described as frequently noted in flight-log discussions.",
  "Les Wexner": "Reported context: described as a noted passenger in some reports.",
  "Doug Band": "Reported context: described as present on many Clinton-associated flights.",
  "Woody Allen": "Reported context: described as appearing in some 2014 manifests with Soon-Yi Previn.",
  "Soon-Yi Previn": "Reported context: described as appearing in some 2014 manifests.",
  "Bill Gates": "Reported context: described as appearing on one flight in 2013.",
  "Lawrence Summers": "Reported context: described as noted on some flights.",
  "Itzhak Perlman": "Reported context: described as an occasional passenger.",
  "Eva Andersson-Dubin": "Reported context: described as appearing across multiple flights with family.",
  "Sarah Ferguson": "Reported context: described as appearing in some mentions.",
};


window.personSourcesByName = {
  "General": [
    "https://en.wikipedia.org/wiki/Little_Saint_James",
    "https://nymag.com/intelligencer/article/who-is-on-jeffrey-epstein-list-names-clients-associates-files-emails.html",
    "https://www.wired.com/story/jeffrey-epstein-island-visitors-data-broker-leak",
    "https://www.wired.com/video/watch/we-tracked-every-visitor-to-epstein-island",
    "https://www.justice.gov/epstein"
  ],
  "Prince Andrew": [
    "https://en.wikipedia.org/wiki/Prominent_individuals_mentioned_in_the_Epstein_files",
    "https://www.aljazeera.com/news/2024/1/4/jeffrey-epstein-list-whose-names-are-on-the-newly-unsealed-documents"
  ],
  "Stephen Hawking": [
    "https://en.wikipedia.org/wiki/Prominent_individuals_mentioned_in_the_Epstein_files",
    "https://nymag.com/intelligencer/article/who-is-on-jeffrey-epstein-list-names-clients-associates-files-emails.html"
  ],
  "Sergey Brin": [
    "https://en.wikipedia.org/wiki/Prominent_individuals_mentioned_in_the_Epstein_files",
    "https://nymag.com/intelligencer/article/who-is-on-jeffrey-epstein-list-names-clients-associates-files-emails.html"
  ],
  "Anne Wojcicki": [
    "https://en.wikipedia.org/wiki/Prominent_individuals_mentioned_in_the_Epstein_files",
    "https://nymag.com/intelligencer/article/who-is-on-jeffrey-epstein-list-names-clients-associates-files-emails.html"
  ],
  "Reid Hoffman": [
    "https://en.wikipedia.org/wiki/Little_Saint_James",
    "https://www.abc.net.au/news/2025-12-21/epstein-files-who-is-named-in-the-released-emails-documents/106026984"
  ],
  "Howard Lutnick": [
    "https://en.wikipedia.org/wiki/Little_Saint_James",
    "https://www.pbs.org/newshour/nation/a-list-of-powerful-men-named-in-the-epstein-files-from-elon-musk-to-former-prince-andrew",
    "https://www.bbc.com/news/articles/cqxynz2l0g2o"
  ],
  "Joanna Rubinstein": [
    "https://nymag.com/intelligencer/article/who-is-on-jeffrey-epstein-list-names-clients-associates-files-emails.html"
  ],
  "Ehud Barak": [
    "https://en.wikipedia.org/wiki/Little_Saint_James",
    "https://nymag.com/intelligencer/article/who-is-on-jeffrey-epstein-list-names-clients-associates-files-emails.html"
  ],
  "David Copperfield": [
    "https://en.wikipedia.org/wiki/Prominent_individuals_mentioned_in_the_Epstein_files"
  ],
  "Ghislaine Maxwell": [
    "https://en.wikipedia.org/wiki/Little_Saint_James"
  ],
  "Les Wexner": [
    "https://en.wikipedia.org/wiki/Little_Saint_James"
  ],
  "Bill Clinton": [
    "https://en.wikipedia.org/wiki/Prominent_individuals_mentioned_in_the_Epstein_files",
    "https://nymag.com/intelligencer/article/who-is-on-jeffrey-epstein-list-names-clients-associates-files-emails.html"
  ],
  "Andrew Farkas": [
    "https://en.wikipedia.org/wiki/Prominent_individuals_mentioned_in_the_Epstein_files"
  ],
  "Thorbjorn Jagland": [
    "https://en.wikipedia.org/wiki/Prominent_individuals_mentioned_in_the_Epstein_files"
  ],
  "Sultan Ahmed bin Sulayem": [
    "https://nymag.com/intelligencer/article/who-is-on-jeffrey-epstein-list-names-clients-associates-files-emails.html"
  ],
  "Roger Schank": [
    "https://nymag.com/intelligencer/article/who-is-on-jeffrey-epstein-list-names-clients-associates-files-emails.html"
  ]
};
